/// A built-in list of common foods with typical nutrition, so a described
/// meal can be matched without going online.
///
/// Generic foods use USDA FoodData Central values (SR Legacy / Foundation),
/// rounded. Israeli staples use typical Israeli label values. They are
/// typical values, not a specific product; the UI says so.
///
/// Pure Dart: no Flutter or DB imports.
library;

import '../../../domain/models.dart';

/// One built-in food. Nutrition is per 100 g.
class BuiltinFood {
  const BuiltinFood(
    this.key,
    this.name,
    this.kcal,
    this.proteinG,
    this.fatG,
    this.carbsG, {
    this.aliases = const [],
    this.servingName,
    this.servingGrams,
    this.preferred = false,
  });

  /// Stable id; saved as the food's `externalId` once it is logged.
  final String key;

  /// Display name, e.g. "Cottage cheese 5%".
  final String name;
  final double kcal;
  final double proteinG;
  final double fatG;
  final double carbsG;

  /// Other ways people say it ("cottage", "gvina levana").
  final List<String> aliases;

  /// A natural portion, e.g. "large egg" = 50 g.
  final String? servingName;
  final double? servingGrams;

  /// The usual pick when a vague name fits several entries (plain "cottage"
  /// means 5%).
  final bool preferred;

  Macros get per100g =>
      Macros(kcal: kcal, proteinG: proteinG, fatG: fatG, carbsG: carbsG);
}

/// The built-in foods, grouped loosely by kind.
const List<BuiltinFood> builtinFoods = [
  // Eggs
  BuiltinFood(
    'egg',
    'Egg',
    143,
    12.6,
    9.5,
    0.7,
    aliases: ['egg', 'boiled egg', 'hard boiled egg', 'whole egg'],
    servingName: 'large egg',
    servingGrams: 50,
    preferred: true,
  ),
  BuiltinFood(
    'fried_egg',
    'Fried egg',
    196,
    13.6,
    14.8,
    0.8,
    aliases: ['fried egg', 'sunny side up'],
    servingName: 'fried egg',
    servingGrams: 46,
  ),
  BuiltinFood(
    'omelette',
    'Omelette / scrambled eggs',
    149,
    10,
    11,
    1.6,
    aliases: ['omelette', 'scrambled eggs', 'scrambled egg'],
    servingName: 'portion (2 eggs)',
    servingGrams: 120,
  ),
  BuiltinFood(
    'egg_white',
    'Egg white',
    52,
    10.9,
    0.2,
    0.7,
    aliases: ['egg white', 'egg whites'],
    servingName: 'egg white',
    servingGrams: 33,
  ),

  // Israeli dairy and spreads
  BuiltinFood(
    'cottage_5',
    'Cottage cheese 5%',
    95,
    11,
    5,
    1.5,
    aliases: ['cottage', 'cottage cheese', 'cottage 5%'],
    servingName: 'tub',
    servingGrams: 250,
    preferred: true,
  ),
  BuiltinFood(
    'cottage_3',
    'Cottage cheese 3%',
    77,
    11,
    3,
    1.5,
    aliases: ['cottage', 'cottage cheese', 'cottage 3%'],
    servingName: 'tub',
    servingGrams: 250,
  ),
  BuiltinFood(
    'white_cheese_5',
    'White cheese 5% (gvina levana)',
    95,
    9,
    5,
    3.5,
    aliases: ['white cheese', 'gvina levana', 'soft white cheese', 'quark'],
  ),
  BuiltinFood('labaneh', 'Labaneh 5%', 89, 6.5, 5, 4.5, aliases: ['labaneh']),
  BuiltinFood(
    'hummus',
    'Hummus (spread)',
    250,
    7,
    19,
    12,
    aliases: ['hummus', 'hummus spread', 'hummus salad'],
    servingName: 'serving (2 tbsp)',
    servingGrams: 30,
  ),
  BuiltinFood(
    'tahini_paste',
    'Tahini (raw paste)',
    595,
    17,
    54,
    21,
    aliases: ['tahini', 'raw tahini', 'tahini paste', 'sesame paste'],
    servingName: 'serving (2 tbsp)',
    servingGrams: 30,
    preferred: true,
  ),
  BuiltinFood(
    'tahini_sauce',
    'Tahini sauce (prepared)',
    300,
    8.5,
    27,
    10.5,
    aliases: ['tahini sauce', 'prepared tahini'],
  ),
  BuiltinFood(
    'israeli_salad',
    'Israeli salad (with oil)',
    55,
    1,
    3.5,
    4,
    aliases: ['israeli salad', 'salad', 'chopped salad', 'vegetable salad'],
    servingName: 'serving',
    servingGrams: 150,
  ),
  BuiltinFood(
    'shakshuka',
    'Shakshuka',
    95,
    5.5,
    6.5,
    4.5,
    aliases: ['shakshuka'],
    servingName: 'serving (2 eggs)',
    servingGrams: 250,
  ),
  BuiltinFood(
    'schnitzel',
    'Chicken schnitzel (breaded, fried)',
    250,
    18,
    13,
    15,
    aliases: ['schnitzel', 'chicken schnitzel'],
    servingName: 'schnitzel',
    servingGrams: 130,
  ),
  BuiltinFood(
    'bamba',
    'Bamba (peanut snack)',
    543,
    16,
    35,
    39,
    aliases: ['bamba', 'peanut snack'],
    servingName: 'small bag',
    servingGrams: 25,
  ),
  BuiltinFood(
    'falafel',
    'Falafel',
    333,
    13.3,
    17.8,
    31.8,
    aliases: ['falafel', 'falafel ball'],
    servingName: 'ball',
    servingGrams: 17,
  ),
  BuiltinFood(
    'chicken_shawarma',
    'Chicken shawarma (meat only)',
    205,
    22,
    12,
    2,
    aliases: ['shawarma', 'chicken shawarma'],
    servingName: 'serving',
    servingGrams: 150,
  ),

  // Milk and yogurt
  BuiltinFood(
    'milk_1',
    'Milk 1%',
    42,
    3.4,
    1,
    5,
    aliases: ['milk 1%', 'low fat milk', 'skim milk'],
  ),
  BuiltinFood(
    'milk_3',
    'Milk 3%',
    60,
    3.3,
    3,
    4.8,
    aliases: ['milk', 'milk 3%', 'whole milk'],
    preferred: true,
  ),
  BuiltinFood(
    'almond_milk',
    'Almond milk, unsweetened',
    15,
    0.6,
    1.2,
    0.3,
    aliases: ['almond milk'],
  ),
  BuiltinFood(
    'yogurt',
    'Yogurt, plain 3%',
    61,
    3.5,
    3.3,
    4.7,
    aliases: ['yogurt', 'plain yogurt', 'natural yogurt'],
    servingName: 'cup',
    servingGrams: 200,
    preferred: true,
  ),
  BuiltinFood(
    'greek_yogurt_0',
    'Greek yogurt 0%',
    59,
    10.2,
    0.4,
    3.6,
    aliases: ['greek yogurt', 'greek yogurt 0%', 'nonfat greek yogurt'],
    servingName: 'cup',
    servingGrams: 170,
    preferred: true,
  ),
  BuiltinFood(
    'greek_yogurt_2',
    'Greek yogurt 2%',
    73,
    10,
    1.9,
    3.9,
    aliases: ['greek yogurt', 'greek yogurt 2%'],
    servingName: 'cup',
    servingGrams: 170,
  ),

  // Cheese, butter, oil
  BuiltinFood(
    'yellow_cheese',
    'Yellow cheese 28% (sliced)',
    355,
    26,
    28,
    0.5,
    aliases: ['yellow cheese', 'cheese', 'sliced cheese', 'emek'],
    servingName: 'slice',
    servingGrams: 20,
    preferred: true,
  ),
  BuiltinFood(
    'cheddar',
    'Cheddar',
    403,
    24.9,
    33.1,
    1.3,
    aliases: ['cheddar'],
    servingName: 'slice',
    servingGrams: 20,
  ),
  BuiltinFood(
    'mozzarella',
    'Mozzarella',
    300,
    22.2,
    22.4,
    2.2,
    aliases: ['mozzarella'],
  ),
  BuiltinFood(
    'feta',
    'Feta cheese',
    264,
    14.2,
    21.3,
    4.1,
    aliases: ['feta', 'feta cheese'],
  ),
  BuiltinFood(
    'parmesan',
    'Parmesan',
    392,
    35.8,
    25.8,
    3.2,
    aliases: ['parmesan', 'parmigiano'],
  ),
  BuiltinFood(
    'cream_cheese',
    'Cream cheese',
    342,
    5.9,
    34.2,
    4.1,
    aliases: ['cream cheese'],
  ),
  BuiltinFood('butter', 'Butter', 717, 0.9, 81.1, 0.1, aliases: ['butter']),
  BuiltinFood(
    'olive_oil',
    'Olive oil',
    884,
    0,
    100,
    0,
    aliases: ['olive oil', 'oil'],
    preferred: true,
  ),
  BuiltinFood(
    'canola_oil',
    'Canola oil',
    884,
    0,
    100,
    0,
    aliases: ['canola oil', 'vegetable oil', 'oil'],
  ),
  BuiltinFood(
    'mayonnaise',
    'Mayonnaise',
    680,
    1,
    75,
    0.6,
    aliases: ['mayonnaise'],
  ),

  // Bread and baked goods
  BuiltinFood(
    'white_bread',
    'White bread',
    265,
    9,
    3.2,
    49,
    aliases: ['bread', 'white bread', 'toast'],
    servingName: 'slice',
    servingGrams: 30,
    preferred: true,
  ),
  BuiltinFood(
    'whole_wheat_bread',
    'Whole wheat bread',
    252,
    12.5,
    3.5,
    43,
    aliases: [
      'whole wheat bread',
      'whole grain bread',
      'brown bread',
      'wholemeal bread',
    ],
    servingName: 'slice',
    servingGrams: 30,
  ),
  BuiltinFood(
    'bread_roll',
    'Bread roll',
    279,
    9.5,
    4.3,
    49.4,
    aliases: ['bread roll', 'roll', 'bun', 'lachmania'],
    servingName: 'roll',
    servingGrams: 60,
  ),
  BuiltinFood(
    'challah',
    'Challah',
    287,
    9.5,
    6,
    47.8,
    aliases: ['challah', 'hallah'],
    servingName: 'slice',
    servingGrams: 40,
  ),
  BuiltinFood(
    'pita',
    'Pita',
    275,
    9.1,
    1.2,
    55.7,
    aliases: ['pita', 'pita bread'],
    servingName: 'pita',
    servingGrams: 90,
    preferred: true,
  ),
  BuiltinFood(
    'whole_wheat_pita',
    'Whole wheat pita',
    266,
    9.8,
    2.6,
    55,
    aliases: ['whole wheat pita'],
    servingName: 'pita',
    servingGrams: 90,
  ),
  BuiltinFood(
    'bagel',
    'Bagel',
    257,
    10,
    1.6,
    50.5,
    aliases: ['bagel'],
    servingName: 'bagel',
    servingGrams: 100,
  ),
  BuiltinFood(
    'tortilla',
    'Flour tortilla',
    312,
    8.3,
    8,
    51.6,
    aliases: ['tortilla', 'wrap', 'laffa'],
    servingName: 'tortilla',
    servingGrams: 45,
  ),
  BuiltinFood(
    'rice_cake',
    'Rice cake',
    387,
    8.2,
    2.8,
    81.5,
    aliases: ['rice cake', 'puffed rice cake'],
    servingName: 'rice cake',
    servingGrams: 9,
  ),
  BuiltinFood(
    'croissant',
    'Croissant',
    406,
    8.2,
    21,
    45.8,
    aliases: ['croissant'],
    servingName: 'croissant',
    servingGrams: 60,
  ),
  BuiltinFood(
    'pancake',
    'Pancake',
    227,
    6.4,
    9.7,
    28.3,
    aliases: ['pancake'],
    servingName: 'pancake',
    servingGrams: 40,
  ),
  BuiltinFood(
    'pizza',
    'Pizza, cheese',
    266,
    11.4,
    10.4,
    33.3,
    aliases: ['pizza', 'cheese pizza'],
    servingName: 'slice',
    servingGrams: 107,
  ),

  // Grains and starches (cooked unless noted)
  BuiltinFood(
    'white_rice',
    'White rice, cooked',
    130,
    2.7,
    0.3,
    28.2,
    aliases: ['rice', 'white rice', 'cooked rice'],
    preferred: true,
  ),
  BuiltinFood(
    'brown_rice',
    'Brown rice, cooked',
    123,
    2.7,
    1,
    25.6,
    aliases: ['brown rice'],
  ),
  BuiltinFood(
    'pasta',
    'Pasta, cooked',
    158,
    5.8,
    0.9,
    30.9,
    aliases: ['pasta', 'spaghetti', 'penne', 'macaroni', 'noodles'],
  ),
  BuiltinFood(
    'quinoa',
    'Quinoa, cooked',
    120,
    4.4,
    1.9,
    21.3,
    aliases: ['quinoa'],
  ),
  BuiltinFood(
    'couscous',
    'Couscous, cooked',
    112,
    3.8,
    0.2,
    23.2,
    aliases: ['couscous'],
  ),
  BuiltinFood(
    'bulgur',
    'Bulgur, cooked',
    83,
    3.1,
    0.2,
    18.6,
    aliases: ['bulgur', 'burghul'],
  ),
  BuiltinFood(
    'oats',
    'Oats (dry)',
    379,
    13.2,
    6.5,
    67.7,
    aliases: ['oats', 'rolled oats', 'oat flakes'],
  ),
  BuiltinFood(
    'oatmeal',
    'Oatmeal, cooked with water',
    71,
    2.5,
    1.5,
    12,
    aliases: ['oatmeal', 'porridge', 'cooked oats'],
    servingName: 'bowl',
    servingGrams: 250,
  ),
  BuiltinFood(
    'cornflakes',
    'Cornflakes',
    357,
    7.5,
    0.4,
    84,
    aliases: ['cornflakes', 'cereal', 'corn flakes'],
  ),
  BuiltinFood('granola', 'Granola', 471, 10, 20, 64, aliases: ['granola']),
  BuiltinFood(
    'potato',
    'Potato, boiled',
    87,
    1.9,
    0.1,
    20.1,
    aliases: ['potato', 'boiled potato'],
    servingName: 'potato',
    servingGrams: 150,
  ),
  BuiltinFood(
    'sweet_potato',
    'Sweet potato, baked',
    90,
    2,
    0.2,
    20.7,
    aliases: ['sweet potato', 'batata'],
    servingName: 'sweet potato',
    servingGrams: 150,
  ),
  BuiltinFood(
    'fries',
    'French fries',
    312,
    3.4,
    15,
    41,
    aliases: ['fries', 'french fries', 'chips'],
    servingName: 'portion',
    servingGrams: 150,
  ),

  // Meat, fish, protein
  BuiltinFood(
    'chicken_breast',
    'Chicken breast, cooked',
    165,
    31,
    3.6,
    0,
    aliases: ['chicken', 'chicken breast', 'grilled chicken'],
    preferred: true,
  ),
  BuiltinFood(
    'chicken_thigh',
    'Chicken thigh, cooked (skinless)',
    209,
    26,
    10.9,
    0,
    aliases: ['chicken thigh', 'pargit'],
  ),
  BuiltinFood(
    'turkey_breast',
    'Turkey breast, cooked',
    147,
    30,
    2,
    0,
    aliases: ['turkey', 'turkey breast'],
  ),
  BuiltinFood(
    'ground_beef',
    'Ground beef, cooked (85% lean)',
    250,
    25.9,
    15.4,
    0,
    aliases: ['ground beef', 'minced beef', 'beef', 'minced meat'],
  ),
  BuiltinFood(
    'steak',
    'Beef steak, cooked',
    250,
    27,
    15.5,
    0,
    aliases: ['steak', 'beef steak', 'entrecote', 'sirloin'],
  ),
  BuiltinFood(
    'hot_dog',
    'Hot dog sausage',
    290,
    11,
    26,
    3,
    aliases: ['hot dog', 'sausage', 'naknik'],
    servingName: 'sausage',
    servingGrams: 50,
  ),
  BuiltinFood(
    'salmon',
    'Salmon, cooked',
    206,
    22.1,
    12.4,
    0,
    aliases: ['salmon'],
  ),
  BuiltinFood(
    'tuna_water',
    'Tuna in water, drained',
    116,
    25.5,
    0.8,
    0,
    aliases: ['tuna', 'tuna in water', 'canned tuna'],
    servingName: 'can (drained)',
    servingGrams: 110,
    preferred: true,
  ),
  BuiltinFood(
    'tuna_oil',
    'Tuna in oil, drained',
    198,
    29.1,
    8.2,
    0,
    aliases: ['tuna in oil'],
    servingName: 'can (drained)',
    servingGrams: 110,
  ),
  BuiltinFood('tofu', 'Tofu, firm', 144, 15.8, 8.7, 2.8, aliases: ['tofu']),
  BuiltinFood(
    'lentils',
    'Lentils, cooked',
    116,
    9,
    0.4,
    20.1,
    aliases: ['lentils', 'lentil'],
  ),
  BuiltinFood(
    'chickpeas',
    'Chickpeas, cooked',
    164,
    8.9,
    2.6,
    27.4,
    aliases: ['chickpeas', 'chickpea'],
  ),
  BuiltinFood(
    'black_beans',
    'Black beans, cooked',
    132,
    8.9,
    0.5,
    23.7,
    aliases: ['beans', 'black beans'],
  ),
  BuiltinFood(
    'whey',
    'Whey protein powder',
    390,
    78,
    6,
    8,
    aliases: ['whey', 'protein powder', 'protein shake', 'protein'],
    servingName: 'scoop',
    servingGrams: 30,
  ),
  BuiltinFood(
    'protein_bar',
    'Protein bar',
    360,
    30,
    12,
    35,
    aliases: ['protein bar'],
    servingName: 'bar',
    servingGrams: 60,
  ),

  // Fruit
  BuiltinFood(
    'banana',
    'Banana',
    89,
    1.1,
    0.3,
    22.8,
    aliases: ['banana'],
    servingName: 'banana',
    servingGrams: 120,
  ),
  BuiltinFood(
    'apple',
    'Apple',
    52,
    0.3,
    0.2,
    13.8,
    aliases: ['apple'],
    servingName: 'apple',
    servingGrams: 180,
  ),
  BuiltinFood(
    'orange',
    'Orange',
    47,
    0.9,
    0.1,
    11.8,
    aliases: ['orange'],
    servingName: 'orange',
    servingGrams: 150,
  ),
  BuiltinFood(
    'clementine',
    'Clementine',
    53,
    0.8,
    0.3,
    13.3,
    aliases: ['clementine', 'mandarin', 'tangerine'],
    servingName: 'clementine',
    servingGrams: 75,
  ),
  BuiltinFood(
    'dates',
    'Dates (medjool)',
    277,
    1.8,
    0.2,
    68.3, // without the 6.7 g of fibre
    aliases: ['date', 'dates', 'medjool'],
    servingName: 'date',
    servingGrams: 8,
  ),
  BuiltinFood(
    'strawberries',
    'Strawberries',
    32,
    0.7,
    0.3,
    7.7,
    aliases: ['strawberry', 'strawberries'],
  ),
  BuiltinFood(
    'blueberries',
    'Blueberries',
    57,
    0.7,
    0.3,
    14.5,
    aliases: ['blueberry', 'blueberries'],
  ),
  BuiltinFood(
    'grapes',
    'Grapes',
    69,
    0.7,
    0.2,
    18.1,
    aliases: ['grapes', 'grape'],
  ),
  BuiltinFood(
    'watermelon',
    'Watermelon',
    30,
    0.6,
    0.2,
    7.6,
    aliases: ['watermelon'],
  ),
  BuiltinFood('mango', 'Mango', 60, 0.8, 0.4, 15, aliases: ['mango']),
  BuiltinFood(
    'pear',
    'Pear',
    57,
    0.4,
    0.1,
    15.2,
    aliases: ['pear'],
    servingName: 'pear',
    servingGrams: 180,
  ),
  BuiltinFood(
    'peach',
    'Peach',
    39,
    0.9,
    0.3,
    9.5,
    aliases: ['peach', 'nectarine'],
    servingName: 'peach',
    servingGrams: 150,
  ),
  BuiltinFood(
    'pomegranate',
    'Pomegranate seeds',
    83,
    1.7,
    1.2,
    18.7,
    aliases: ['pomegranate'],
  ),
  BuiltinFood(
    'avocado',
    'Avocado',
    160,
    2,
    14.7,
    8.5,
    aliases: ['avocado'],
    servingName: 'avocado (flesh)',
    servingGrams: 150,
  ),

  // Vegetables
  BuiltinFood(
    'tomato',
    'Tomato',
    18,
    0.9,
    0.2,
    3.9,
    aliases: ['tomato', 'tomatoes'],
    servingName: 'tomato',
    servingGrams: 120,
  ),
  BuiltinFood(
    'cucumber',
    'Cucumber',
    15,
    0.7,
    0.1,
    3.6,
    aliases: ['cucumber', 'cucumbers'],
    servingName: 'cucumber',
    servingGrams: 150,
  ),
  BuiltinFood(
    'carrot',
    'Carrot',
    41,
    0.9,
    0.2,
    9.6,
    aliases: ['carrot'],
    servingName: 'carrot',
    servingGrams: 60,
  ),
  BuiltinFood(
    'bell_pepper',
    'Bell pepper',
    31,
    1,
    0.3,
    6,
    aliases: ['pepper', 'bell pepper', 'red pepper'],
    servingName: 'pepper',
    servingGrams: 120,
  ),
  BuiltinFood(
    'onion',
    'Onion',
    40,
    1.1,
    0.1,
    9.3,
    aliases: ['onion'],
    servingName: 'onion',
    servingGrams: 110,
  ),
  BuiltinFood(
    'lettuce',
    'Lettuce',
    15,
    1.4,
    0.2,
    2.9,
    aliases: ['lettuce', 'green salad', 'leaves'],
  ),
  BuiltinFood(
    'broccoli',
    'Broccoli, cooked',
    35,
    2.4,
    0.4,
    7.2,
    aliases: ['broccoli'],
  ),
  BuiltinFood(
    'cauliflower',
    'Cauliflower',
    25,
    1.9,
    0.3,
    5,
    aliases: ['cauliflower'],
  ),
  BuiltinFood('spinach', 'Spinach', 23, 2.9, 0.4, 3.6, aliases: ['spinach']),
  BuiltinFood(
    'mushrooms',
    'Mushrooms',
    22,
    3.1,
    0.3,
    3.3,
    aliases: ['mushroom', 'mushrooms'],
  ),
  BuiltinFood(
    'zucchini',
    'Zucchini',
    17,
    1.2,
    0.3,
    3.1,
    aliases: ['zucchini', 'courgette'],
    servingName: 'zucchini',
    servingGrams: 200,
  ),
  BuiltinFood(
    'pickles',
    'Pickled cucumber',
    11,
    0.3,
    0.2,
    2.3,
    aliases: ['pickle', 'pickles', 'pickled cucumber'],
    servingName: 'pickle',
    servingGrams: 35,
  ),
  BuiltinFood(
    'olives',
    'Olives',
    115,
    0.8,
    10.7,
    6.3,
    aliases: ['olive', 'olives'],
    servingName: 'olive',
    servingGrams: 4,
  ),

  // Nuts and seeds
  BuiltinFood(
    'almonds',
    'Almonds',
    579,
    21.2,
    49.9,
    21.6,
    aliases: ['almonds', 'almond'],
  ),
  BuiltinFood(
    'walnuts',
    'Walnuts',
    654,
    15.2,
    65.2,
    13.7,
    aliases: ['walnuts', 'walnut'],
  ),
  BuiltinFood(
    'cashews',
    'Cashews',
    553,
    18.2,
    43.8,
    30.2,
    aliases: ['cashews', 'cashew'],
  ),
  BuiltinFood(
    'peanuts',
    'Peanuts',
    567,
    25.8,
    49.2,
    16.1,
    aliases: ['peanuts', 'peanut'],
  ),
  BuiltinFood(
    'pistachios',
    'Pistachios',
    560,
    20.2,
    45.3,
    27.2,
    aliases: ['pistachios', 'pistachio'],
  ),
  BuiltinFood(
    'peanut_butter',
    'Peanut butter',
    588,
    25,
    50,
    20,
    aliases: ['peanut butter'],
  ),

  // Sweets and snacks
  BuiltinFood(
    'milk_chocolate',
    'Milk chocolate',
    535,
    7.7,
    29.7,
    59.4,
    aliases: ['chocolate', 'milk chocolate'],
    preferred: true,
  ),
  BuiltinFood(
    'dark_chocolate',
    'Dark chocolate 70%',
    598,
    7.8,
    42.6,
    45.9,
    aliases: ['dark chocolate'],
  ),
  BuiltinFood('sugar', 'Sugar', 387, 0, 0, 100, aliases: ['sugar']),
  BuiltinFood(
    'honey',
    'Honey',
    304,
    0.3,
    0,
    82.4,
    aliases: ['honey'],
    servingName: 'tbsp',
    servingGrams: 21,
  ),
  BuiltinFood(
    'jam',
    'Jam',
    278,
    0.4,
    0.1,
    68.9,
    aliases: ['jam', 'jelly', 'preserves'],
    servingName: 'tbsp',
    servingGrams: 20,
  ),
  BuiltinFood(
    'ice_cream',
    'Ice cream, vanilla',
    207,
    3.5,
    11,
    23.6,
    aliases: ['ice cream'],
  ),
  BuiltinFood(
    'cookie',
    'Chocolate chip cookie',
    488,
    5.4,
    24,
    64,
    aliases: ['cookie', 'cookies', 'biscuit'],
    servingName: 'cookie',
    servingGrams: 15,
  ),
  BuiltinFood(
    'pretzels',
    'Pretzels',
    380,
    10,
    3,
    80,
    aliases: ['pretzels', 'pretzel', 'beygale'],
  ),
  BuiltinFood(
    'potato_chips',
    'Potato chips',
    536,
    7,
    34.6,
    52.9,
    aliases: ['potato chips', 'crisps'],
  ),

  // Drinks
  BuiltinFood(
    'coffee_black',
    'Coffee, black',
    2,
    0.1,
    0,
    0,
    aliases: ['coffee', 'black coffee', 'espresso', 'americano'],
    servingName: 'cup',
    servingGrams: 240,
  ),
  BuiltinFood(
    'coffee_milk',
    'Coffee with milk (latte)',
    40,
    2.2,
    1.9,
    3.3,
    aliases: [
      'coffee with milk',
      'latte',
      'cappuccino',
      'cafe hafuch',
      'hafuch',
      'flat white',
    ],
    servingName: 'cup',
    servingGrams: 240,
  ),
  BuiltinFood(
    'orange_juice',
    'Orange juice',
    45,
    0.7,
    0.2,
    10.4,
    aliases: ['orange juice', 'juice'],
    servingName: 'glass',
    servingGrams: 240,
  ),
  BuiltinFood(
    'cola',
    'Cola',
    42,
    0,
    0,
    10.6,
    aliases: ['cola', 'coca cola', 'soda'],
    servingName: 'can',
    servingGrams: 330,
  ),
  BuiltinFood(
    'cola_zero',
    'Cola zero',
    0.3,
    0,
    0,
    0,
    aliases: ['cola zero', 'diet cola', 'coke zero', 'diet coke'],
    servingName: 'can',
    servingGrams: 330,
  ),
];

final Map<String, BuiltinFood> _byKey = {
  for (final f in builtinFoods) f.key: f,
};

/// The built-in food with [key], or null.
BuiltinFood? builtinByKey(String key) => _byKey[key];
